### ISSUE TITLE
Package['gcc'] causes issues with many other modules that 'include gcc'

### ISSUE THREAD

**Issue by aamerik** [echocat/puppet-graphite#166] opened 2015-03-27 18:53 UTC
Hi.  Thank you for this module.  Im trying to use it but keep running into issues due to https://github.com/echocat/puppet-graphite/blob/master/manifests/params.pp#L115 and other modules that try to 'include gcc' (puppetlabs-gcc).  Could you please help find a workaround and maybe consider including puppetlabs-gcc as a dependency instead of force installing gcc using the Package resource.

Thank you!

**Comment by dwerder** [comment] 2015-03-27 19:40
A shortcut would be to just remove the gcc from the list and use the puppetlabs-gcc. But you are right. Maybe its better to use an official module.

**Comment by everestx** [comment] 2015-03-27 21:24
Even better would be to use the ensure_package() function from stdlib when installing packages. Requiring all these other puppet modules gets very hairy. The gcc module should use ensure_package() too.

**Comment by dwerder** [comment] 2015-03-31 07:15
@everestx
ensure_package() can be helpful, but at the end its just a wrapper/shorter for "if ! defined then" , which has its siteeffects too. Furthermore I am not the maintainer of the puppetlabs-gcc module. So I can not ensure that they use ensure_package()

@aamerik 
The graphite module was designed as an stand-alone module at the beginning. And I am not sure if a want to start to use all that possible modules out there. For example you are using puppetlabs-gcc. Other peaple may use other modules. If I include or make a hard require for puppetlabs-gcc they will get problems. Another solution will be to not provide gcc at all in this module and just mention it in the readme. But then this module will not work out of the box anymore.

**Comment by decibelhertz** [comment] 2015-06-14 13:07
With the large array of packages you have, I think `ensure_packages()` is the best choice; I use it a lot, but it does result in weird failure modes if one call to the function sets some parameters that the other does not.

As such, I suggest you omit extra arguments, as _puppetlabs-gcc_ does, and things would function fine.  If you're worried about edge cases, suggest you provide a user-controllable boolean:
```puppet
class graphite::install inherits graphite::params(
  $managepkgs = true,
) {
  validate_bool($managepkgs)
  # ...
  if $managepkgs { ensure_packages($::graphite::params::graphitepkgs) }
  package{ 'django-tagging':
      ensure => $::graphite::gr_django_tagging_ver,
      name   => $::graphite::gr_django_tagging_pkg,
      require => Package[$::graphite::params::graphitepkgs],
  }->
```
As a knock-on effect of all this, you'd need to explicitly define pip as the *provider* for the classes you need, which I think is a better approach, since overriding the default provider can have strange consequences for subsequent installing.  E.G.
```puppet
  create_resources('package',{
    'django-tagging' => {
      ensure => $::graphite::gr_django_tagging_ver,
      name   => $::graphite::gr_django_tagging_pkg,
    },
    'twisted' => {
      ensure => $::graphite::gr_twisted_ver,
      name   => $::graphite::gr_twisted_pkg,
    },
    'txamqp' => {
      ensure => $::graphite::gr_txamqp_ver,
      name   => $::graphite::gr_txamqp_pkg,
    },
    'graphite-web' => {
      ensure => $::graphite::gr_graphite_ver,
      name   => $::graphite::gr_graphite_pkg,
    },
    'carbon' => {
      ensure => $::graphite::gr_carbon_ver,
      name   => $::graphite::gr_carbon_pkg,
    },
    'whisper' => {
      ensure => $::graphite::gr_whisper_ver,
      name   => $::graphite::gr_whisper_pkg,
    },
  },{
    provider => 'pip',
    require  => Package[
      $::graphite::params::graphitepkgs,
      $::graphite::params::python_pip_pkg,
      $::graphite::params::python_dev_pkg,
    ],
  })
```

**Comment by dwerder** [comment] 2015-06-15 13:06
Do you want to provide a PR?

**Comment by decibelhertz** [comment] 2015-06-28 15:09
Sure.  Did that at https://github.com/echocat/puppet-graphite/pull/203

**Comment by decibelhertz** [comment] 2015-06-29 15:47
With https://github.com/echocat/puppet-graphite/pull/203 merged in, I think this issue is closed?  _puppetlabs-gcc_, at least for now uses `ensure_packages()` (see https://github.com/puppetlabs/puppetlabs-gcc/blob/master/manifests/init.pp#L17).  `ensure_packages()` will not conflict with other function calls that do not use the optional second argument, e.g. `ensure_packages('gcc')` (not `ensure_packages('gcc', { ensure => present })`), as well as calls like `package { 'gcc': }`.

**Closed** 2015-07-07 10:13 UTC
Labels: enhancement
